name: CI-Pipeline

# Controls when the workflow will run, when comment is created
on:
  issue_comment:
    types:
      - created
jobs:
  call-golang-ci-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-golang-ci.yml@v1.17.1
    secrets: inherit
